FROM python:2.7.13

EXPOSE 5001

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/database
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY movies.py /usr/src/app/movies.py
COPY database/movies.json /usr/src/app/database

CMD [ "python", "movies.py" ]
