FROM python:2.7.13

EXPOSE 5004

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/database
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY bookings.py /usr/src/app/bookings.py
COPY database/bookings.json /usr/src/app/database

CMD [ "python", "bookings.py" ]
