FROM python:2.7.13

EXPOSE 5002

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/database
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY user.py /usr/src/app/user.py
COPY database/users.json /usr/src/app/database

CMD [ "python", "user.py" ]
